// Code generated by goctl. DO NOT EDIT.
package types

type WsConnectRequest struct {
	ID int `path:"id"`
}

type WsRequestItem struct {
	Message string `json:"message"`
	ToID    []int  `json:"to_id,omitempty"`
}

type WsResponseItem struct {
	Message string `json:"message"`
	FromID  int    `json:"from_id"`
	Time    int64  `json:"time"`
}
